# Generated by Django 5.0.14 on 2026-05-11 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('report_day', models.PositiveIntegerField(help_text='Sequential day number (e.g., 1, 2, 8)')),
                ('hours_today', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hours_total', models.DecimalField(decimal_places=1, max_digits=4)),
                ('task_description', models.TextField()),
                ('discipline_score', models.PositiveIntegerField()),
                ('discipline_max', models.PositiveIntegerField()),
                ('visibility_status', models.BooleanField(default=False, verbose_name='Posted Status Update')),
                ('visibility_twitter', models.BooleanField(default=False, verbose_name='Posted on Twitter/X')),
                ('visibility_comment', models.BooleanField(default=False, verbose_name='Left a Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-report_day'],
                'unique_together': {('user', 'report_day')},
            },
        ),
    ]
